GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikxpc2EiLCJpZCI6IjY4ZjNiYzYxMzRkM2FmNjE0Yzk2ZDdkZSIsImlhdCI6MTc2MDgwNDA2OSwiZXhwIjoxNzYwODA3NjY5fQ.X1mbwlgCXpbThB-cY8fOgY_hrGbO--3UTHKFlS6jGmo
###

POST http://localhost:3003/api/blogs
content-Type: application/json

{
    "_id": "5a422a851b54a676234d17f7",
    "title": "React patterns 2",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "__v": 0
  }

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-Type: application/json

{
    "_id": "5a422a851b54a676234d17f7",
    "title": "React patterns 3",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "__v": 0
  }
